-- =============================================================
-- Table       : TBL_INVENTORY
-- Schema      : PUBLISH | Database : SC_DEV
-- Description : Published inventory fact table
-- =============================================================
USE DATABASE SC_DEV;
USE SCHEMA PUBLISH;

CREATE OR REPLACE TABLE TBL_INVENTORY (
    INVENTORY_KEY       NUMBER AUTOINCREMENT PRIMARY KEY,
    PRODUCT_CODE        VARCHAR(50) NOT NULL,
    PRODUCT_NAME        VARCHAR(255),
    WAREHOUSE_CODE      VARCHAR(50),
    WAREHOUSE_LOCATION  VARCHAR(255),
    QUANTITY_ON_HAND    NUMBER(18,3),
    QUANTITY_RESERVED   NUMBER(18,3) DEFAULT 0,
    QUANTITY_AVAILABLE  NUMBER(18,3),
    REORDER_POINT       NUMBER(18,3),
    REORDER_QUANTITY    NUMBER(18,3),
    UNIT_COST           NUMBER(18,4),
    TOTAL_VALUE         NUMBER(18,2),
    LAST_MOVEMENT_DATE  DATE,
    SOURCE_SYSTEM       VARCHAR(50),
    AS_OF_DATE          DATE,
    CREATED_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
