-- =============================================================
-- Script      : 02_schemas.sql
-- Description : Create all 80 schemas (5 schemas x 16 databases)
-- =============================================================
USE ROLE SYSADMIN;

-- ── Supply Chain Schemas ───────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS SC_DEV.LANDING;
CREATE SCHEMA IF NOT EXISTS SC_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS SC_DEV.CURATED;
CREATE SCHEMA IF NOT EXISTS SC_DEV.PUBLISH;
CREATE SCHEMA IF NOT EXISTS SC_DEV.REPORTING;

CREATE SCHEMA IF NOT EXISTS SC_QA.LANDING;
CREATE SCHEMA IF NOT EXISTS SC_QA.STAGING;
CREATE SCHEMA IF NOT EXISTS SC_QA.CURATED;
CREATE SCHEMA IF NOT EXISTS SC_QA.PUBLISH;
CREATE SCHEMA IF NOT EXISTS SC_QA.REPORTING;

CREATE SCHEMA IF NOT EXISTS SC_PPD.LANDING;
CREATE SCHEMA IF NOT EXISTS SC_PPD.STAGING;
CREATE SCHEMA IF NOT EXISTS SC_PPD.CURATED;
CREATE SCHEMA IF NOT EXISTS SC_PPD.PUBLISH;
CREATE SCHEMA IF NOT EXISTS SC_PPD.REPORTING;

CREATE SCHEMA IF NOT EXISTS SC_PROD.LANDING;
CREATE SCHEMA IF NOT EXISTS SC_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS SC_PROD.CURATED;
CREATE SCHEMA IF NOT EXISTS SC_PROD.PUBLISH;
CREATE SCHEMA IF NOT EXISTS SC_PROD.REPORTING;

-- ── Customer Schemas ───────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS CUST_DEV.LANDING;
CREATE SCHEMA IF NOT EXISTS CUST_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS CUST_DEV.CURATED;
CREATE SCHEMA IF NOT EXISTS CUST_DEV.PUBLISH;
CREATE SCHEMA IF NOT EXISTS CUST_DEV.REPORTING;

CREATE SCHEMA IF NOT EXISTS CUST_QA.LANDING;
CREATE SCHEMA IF NOT EXISTS CUST_QA.STAGING;
CREATE SCHEMA IF NOT EXISTS CUST_QA.CURATED;
CREATE SCHEMA IF NOT EXISTS CUST_QA.PUBLISH;
CREATE SCHEMA IF NOT EXISTS CUST_QA.REPORTING;

CREATE SCHEMA IF NOT EXISTS CUST_PPD.LANDING;
CREATE SCHEMA IF NOT EXISTS CUST_PPD.STAGING;
CREATE SCHEMA IF NOT EXISTS CUST_PPD.CURATED;
CREATE SCHEMA IF NOT EXISTS CUST_PPD.PUBLISH;
CREATE SCHEMA IF NOT EXISTS CUST_PPD.REPORTING;

CREATE SCHEMA IF NOT EXISTS CUST_PROD.LANDING;
CREATE SCHEMA IF NOT EXISTS CUST_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS CUST_PROD.CURATED;
CREATE SCHEMA IF NOT EXISTS CUST_PROD.PUBLISH;
CREATE SCHEMA IF NOT EXISTS CUST_PROD.REPORTING;

-- ── HR Schemas ─────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS HR_DEV.LANDING;
CREATE SCHEMA IF NOT EXISTS HR_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS HR_DEV.CURATED;
CREATE SCHEMA IF NOT EXISTS HR_DEV.PUBLISH;
CREATE SCHEMA IF NOT EXISTS HR_DEV.REPORTING;

CREATE SCHEMA IF NOT EXISTS HR_QA.LANDING;
CREATE SCHEMA IF NOT EXISTS HR_QA.STAGING;
CREATE SCHEMA IF NOT EXISTS HR_QA.CURATED;
CREATE SCHEMA IF NOT EXISTS HR_QA.PUBLISH;
CREATE SCHEMA IF NOT EXISTS HR_QA.REPORTING;

CREATE SCHEMA IF NOT EXISTS HR_PPD.LANDING;
CREATE SCHEMA IF NOT EXISTS HR_PPD.STAGING;
CREATE SCHEMA IF NOT EXISTS HR_PPD.CURATED;
CREATE SCHEMA IF NOT EXISTS HR_PPD.PUBLISH;
CREATE SCHEMA IF NOT EXISTS HR_PPD.REPORTING;

CREATE SCHEMA IF NOT EXISTS HR_PROD.LANDING;
CREATE SCHEMA IF NOT EXISTS HR_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS HR_PROD.CURATED;
CREATE SCHEMA IF NOT EXISTS HR_PROD.PUBLISH;
CREATE SCHEMA IF NOT EXISTS HR_PROD.REPORTING;

-- ── Analytics Schemas ──────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS ANL_DEV.LANDING;
CREATE SCHEMA IF NOT EXISTS ANL_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS ANL_DEV.CURATED;
CREATE SCHEMA IF NOT EXISTS ANL_DEV.PUBLISH;
CREATE SCHEMA IF NOT EXISTS ANL_DEV.REPORTING;

CREATE SCHEMA IF NOT EXISTS ANL_QA.LANDING;
CREATE SCHEMA IF NOT EXISTS ANL_QA.STAGING;
CREATE SCHEMA IF NOT EXISTS ANL_QA.CURATED;
CREATE SCHEMA IF NOT EXISTS ANL_QA.PUBLISH;
CREATE SCHEMA IF NOT EXISTS ANL_QA.REPORTING;

CREATE SCHEMA IF NOT EXISTS ANL_PPD.LANDING;
CREATE SCHEMA IF NOT EXISTS ANL_PPD.STAGING;
CREATE SCHEMA IF NOT EXISTS ANL_PPD.CURATED;
CREATE SCHEMA IF NOT EXISTS ANL_PPD.PUBLISH;
CREATE SCHEMA IF NOT EXISTS ANL_PPD.REPORTING;

CREATE SCHEMA IF NOT EXISTS ANL_PROD.LANDING;
CREATE SCHEMA IF NOT EXISTS ANL_PROD.STAGING;
CREATE SCHEMA IF NOT EXISTS ANL_PROD.CURATED;
CREATE SCHEMA IF NOT EXISTS ANL_PROD.PUBLISH;
CREATE SCHEMA IF NOT EXISTS ANL_PROD.REPORTING;
